name: SmartGym CI/CD REAL (Producción)

on: [push, pull_request]

jobs:
  # ---------------------------------------------------
  # TRABAJO 1: BACKEND (JAVA SPRING BOOT REAL)
  # ---------------------------------------------------
  backend-real:
    runs-on: ubuntu-latest
    
    # AQUÍ ESTÁ LA MAGIA: Le decimos que entre a la carpeta 'backend'
    defaults:
      run:
        working-directory: ./backend

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: smartgym_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Clonar código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # COMANDO REAL: Maven descargará internet entero y compilará tu Java
      - name: Compilar con Maven (Real)
        run: mvn clean package -DskipTests

  # ---------------------------------------------------
  # TRABAJO 2: FRONTEND (ANGULAR REAL)
  # ---------------------------------------------------
  frontend-real:
    runs-on: ubuntu-latest

    # AQUÍ ESTÁ LA MAGIA: Le decimos que entre a la carpeta 'frontend'
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Clonar código
        uses: actions/checkout@v4

      - name: Configurar Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Instalar dependencias (Real)
        run: npm install --legacy-peer-deps
        
      - name: Compilar Angular (Real)
        run: npm run build -- --configuration production

  # ---------------------------------------------------
  # TRABAJO 3: DEPLOY (Solo si todo lo anterior funciona)
  # ---------------------------------------------------
  deploy:
    needs: [backend-real, frontend-real]
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar
        run: echo "¡Éxito total! El código de SmartGym (Backend y Frontend) es válido y compilable."
